numerals/config/routes.rb
Enumerals::Application.routes.draw do
  match 'translate/index' => 'translate#index', :as => 'translate', :via => [:get]
  match 'translate/do_translate' => 'translate#do_translate', :as => 'do_translate', :via => [:post, :get]

end

numerals/app/controllers/main_controller.rb
require 'numeral_converter'

class MainController < ApplicationController
  def index
    unless params[:number].blank? || params[:number].is_a?(Numeric)
      @result = NumeralConverter.new.convert(params[:number].to_i)
    else
      @result = ""
    end
    @original_number = params[:number]
  end
end

numerals/app/controllers/translate_controller.rb
class TranslateController < ApplicationController
  def index
    
  end

  def do_translate
    @result = EnglishNumerals.new.translate(params[:number].to_i)
    respond_to do |format|
      format.json do
        render :json => {:result => @result}
      end
      format.js
    end
  end
end

numerals/app/helpers/translate_helper.rb
module TranslateHelper
end

numerals/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enumerals</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

numerals/app/views/main/index.html.erb
<html>
<head/>
<body>
<%= form_tag do %>
	<%= text_field_tag :number, nil, {:class => "number"} %>
	<%= submit_tag "Submit", :class => "submit" %>
<% end %>
<hr/>
<div class="original-number"><%= @original_number %></div>:<div class="result"><%= @result %></div>
</body>
</html>

numerals/app/views/translate/do_translate.js.erb
jQuery("#result").html('<%= @result %>');
jQuery("#number").reset();

numerals/app/views/translate/index.erb
<%= form_tag(do_translate_path, :remote => true) do %>
	<%= text_field_tag('number', nil, :id=> 'number') %>
	<%= submit_tag('do the trick') %>
<% end %>

<div id="result">
</div>