bwphoto/fb_sg/config/routes.rb
RailsCarrierwave::Application.routes.draw do
  resources :bwimages

  namespace :api do
    resources :bwimages
  end

  root to: 'bwimages#index'
  mount Resque::Server, :at => '/resque'

end

bwphoto/fb_sg/app/models/bwimage.rb
class Bwimage < ActiveRecord::Base
  attr_accessible :photo, :photo_cache, :url, :filename, :original_filename,
                  :title, :author, :taken_at, :camera, :file

  attr_accessor :original_filename, :file

  mount_uploader :photo, PhotoUploader

  #after_save :process_photo
  before_validation :convert_base64

  validates :title, presence: true
  validates :author, presence: true
  validates :camera, presence: true
  validates :taken_at, presence: true

  include AASM
  aasm :column => 'status' do
    state :draft, :initial => true
    state :downloading
    state :processing, :enter => :recreate_delayed_versions!
    state :finished
    state :download_failed
    state :processing_failed

    event :download do
      transitions :from => :draft, :to => :downloading
    end

    event :process, :after => :finish! do
      transitions :from => [:draft, :downloading], :to => :processing
    end

    event :finish do
      transitions :from => :processing, :to => :finished
    end

    event :fail do
      transitions :from => :draft, :to => :download_failed
      transitions :from => :downloading, :to => :processing_failed
    end
  end

  # http://code.dblock.org/carrierwave-delayjob-processing-of-selected-versions
  def recreate_delayed_versions!
    photo.is_processing_delayed = true
    photo.recreate_versions!
  rescue
    fail!
  end

  def process_photo
    if url.present?
      Resque.enqueue(BwimageTask::Remote, id, url)
    else
      Resque.enqueue(BwimageTask::Local, id)
    end
  end

  private

  def convert_base64
    # http://stackoverflow.com/questions/9854916/base64-upload-from-android-java-to-ror-carrierwave
    if file.present?
      tempfile = Tempfile.new("fileupload")
      tempfile.binmode
      #get the file and decode it with base64 then write it to the tempfile
      tempfile.write(Base64.decode64(file))

      #create a new uploaded file
      uploaded_file = ActionDispatch::Http::UploadedFile.new(:tempfile => tempfile, 
                                                             :filename => filename || SecureRandom.hex(4), 
                                                             :original_filename => filename || SecureRandom.hex(4))
      self.photo = uploaded_file
    end
  end

end

bwphoto/fb_sg/app/models/faye_client.rb
class FayeClient
  def self.photo_added(photo)
    broadcast("/photos/updated", photo.as_json)
  end

  def self.broadcast(channel, data)
    if EM.reactor_running?
      Rails.logger.debug "EM reactor running, broadcasting"
      $faye_client.publish channel, data
    end
  end
end

bwphoto/fb_sg/app/controllers/api/bwimages_controller.rb
class Api::BwimagesController < ApplicationController

  # POST /bwimages
  # POST /bwimages.json
  def create

    begin
      data = JSON.parse(params[:bwimage])
    rescue TypeError => e
      logger.error "Cannot parse params as JSON #{params[:bwimage]}"
    end

    @bwimage = Bwimage.new(data)

    respond_to do |format|
      if @bwimage.save
        @bwimage.process_photo
        FayeClient::photo_added(@bwimage)
        format.html { head 200 }
        format.json { head 200 }
        # format.json { render json: @bwimage, status: :created, location: @bwimage }
      else
        format.html { render json: @bwimage.errors, status: :unprocessable_entity }
        format.json { render json: @bwimage.errors, status: :unprocessable_entity }
      end
    end
  end

end

bwphoto/fb_sg/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

bwphoto/fb_sg/app/controllers/bwimages_controller.rb
class BwimagesController < ApplicationController
  # GET /bwimages
  # GET /bwimages.json
  def index
    @bwimages = Bwimage.paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bwimages }
    end
  end

  # GET /bwimages/1
  # GET /bwimages/1.json
  def show
    @bwimage = Bwimage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bwimage }
    end
  end

  # GET /bwimages/new
  # GET /bwimages/new.json
  def new
    @bwimage = Bwimage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bwimage }
    end
  end

  # GET /bwimages/1/edit
  def edit
    @bwimage = Bwimage.find(params[:id])
  end

  # POST /bwimages
  # POST /bwimages.json
  def create
    @bwimage = Bwimage.new(params[:bwimage])

    respond_to do |format|
      if @bwimage.save
        format.html { redirect_to @bwimage, notice: 'Bwimage was successfully created.' }
        format.json { render json: @bwimage, status: :created, location: @bwimage }
      else
        format.html { render action: "new" }
        format.json { render json: @bwimage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bwimages/1
  # PUT /bwimages/1.json
  def update
    @bwimage = Bwimage.find(params[:id])

    respond_to do |format|
      if @bwimage.update_attributes(params[:bwimage])
        format.html { redirect_to @bwimage, notice: 'Bwimage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bwimage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bwimages/1
  # DELETE /bwimages/1.json
  def destroy
    @bwimage = Bwimage.find(params[:id])
    @bwimage.destroy

    respond_to do |format|
      format.html { redirect_to bwimages_url }
      format.json { head :no_content }
    end
  end
end

bwphoto/fb_sg/app/helpers/api/bwimages_helper.rb
module Api::BwimagesHelper
end

bwphoto/fb_sg/app/helpers/application_helper.rb
module ApplicationHelper
end

bwphoto/fb_sg/app/helpers/bwimages_helper.rb
module BwimagesHelper
end

bwphoto/fb_sg/app/views/bwimages/_form.html.erb
<%= form_for(@bwimage, :html => { :multipart => true }) do |f| %>
  <% if @bwimage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bwimage.errors.count, "error") %> prohibited this bwimage from being saved:</h2>

      <ul>
      <% @bwimage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :camera %><br />
    <%= f.text_field :camera %>
  </div>
  <div class="field">
    <%= f.label :taken_at %><br />
    <%= f.date_select :taken_at %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
    <%= f.hidden_field :photo_cache %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bwphoto/fb_sg/app/views/bwimages/edit.html.erb
<h1>Editing bwimage</h1>

<%= render 'form' %>

<%= link_to 'Show', @bwimage %> |
<%= link_to 'Back', bwimages_path %>

bwphoto/fb_sg/app/views/bwimages/index.html.erb
<div id="app"></div>

<script type="text/javascript" charset="utf-8">
  jQuery(function(){
      // onready, instantiate App
      window.app = new App({el: $("#app")})
      });
</script>

bwphoto/fb_sg/app/views/bwimages/new.html.erb
<h1>New bwimage</h1>

<%= render 'form' %>

<%= link_to 'Back', bwimages_path %>

bwphoto/fb_sg/app/views/bwimages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bwimage.title %>
</p>

<p>
<b>Photo:</b>
  <%= image_tag @bwimage.photo_url.to_s %>
</p>

<%= link_to 'Edit', edit_bwimage_path(@bwimage) %> |
<%= link_to 'Back', bwimages_path %>

bwphoto/fb_sg/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCarrierwave</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", "/faye.js" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>